#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# This file is part of smartd_pyngui

"""
This script generates all necessary private keys for smartd_pyngui to store it's values

"""

import os
from datetime import datetime
from configparser_crypt.fernet_backend import ConfigParserCrypt
from ofunctions import revac


PYTHON_HEADER = '#! /usr/bin/env python\n' \
                '# -*- coding: utf-8 -*-\n' \
                '#\n' \
                '# This file was generated by smartd_pyngui secret generator on %s\n\n' % \
                datetime.today()


def generate_config_key():
    """
    AES encryption key for config files

    """

    c = ConfigParserCrypt()
    key = c.generate_key()

    body = '# Is revac encoded\nAES_ENCRYPTION_KEY = %s' % revac(key)
    key_file = os.path.join('PRIVATE', 'aes_key.py')


    with open(key_file, 'w') as fp:
        fp.write(PYTHON_HEADER)
        fp.write(body)
    print('Config key written to {0}.'.format(key_file))


generate_config_key()
