#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file was generated by imf secret generator on 2020-04-12 17:56:58.004991

# Is revac encoded
AES_ENCRYPTION_KEY = b'YFYoZ8CBs91B3VFQuY5fdAf_RgQzifiHXREQTfBlDx=Q'