# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import warnings
import sys
import Tkinter
import tkinter.scrolledtext
import tkColorChooser
import datetime
import tkFileDialog
import tkFont
import tkinter
import pickle
import textwrap
import ScrolledText
import time
import ttk
import tkinter.font
import math
import random
import calendar
import inspect
import tkinter.colorchooser

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

